apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: hue-intern-service
  metrics:
  - name: success-rate
    interval: 5s
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 0.9
    failureCondition: result[0] < 0.9
    failureLimit: 1
    provider:
      prometheus:
        address: https://monitoring.googleapis.com/v1/projects/stage-kora-dokbua/location/global/prometheus/api/v1/query
        # timeout is expressed in seconds
        timeout: 40
        headers:
        - key: "Authorization"
          value: "Bearer ya29.a0AXooCgv481nMqgJVit6Y03zmu0nB0Af-3fHush3DdnY7hZlk6WTeJbfEOwifbp4lZ4_5oL3WEYvcYbzJiLPp7DaiJtLaULsnmp9l-R8DGeGZixVvZwYIF1yn_Cmpfa3XmuiTnaQChHZx7AQ9ChL1UJh4q_54asON6P2zpICTAVn1aCgYKARYSARESFQHGX2MiKMiR00MuRudwBqDaKaR3zw0179"
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"hue-intern-service.default.svc.cluster.local",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"hue-intern-service.default.svc.cluster.local"}[5m]
          ))
