apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: hue-intern-service
  metrics:
  - name: success-rate
    interval: 10s
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: len(result) > 0 && result[0] == 0.00
    # failureCondition: len(result) > 0 && result[0] > -1.00
    # failure limit has to at least 3 for the analysis to work properly
    failureLimit: 3
    provider:
      prometheus:
        address: http://34.118.231.119
        # timeout is expressed in seconds
        timeout: 40
        headers:
        - key: X-Scope-Org-ID
          value: tenant_a
        # query: 'promhttp_metric_handler_requests_total{code="200", job="monitor hue-intern"}'
        query: 'sum(promhttp_metric_handler_requests_total{code=~"5.*", job="monitor hue-intern"})'


