apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: prometheus-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hue-intern
  endpoints:
  - port: metrics
    interval: 30s